name: CI

on: [push, pull_request]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: master
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Packages
        run: npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: dist

      - name: Find symlinks
        run: find dist -type l
      - name: Find hardlinks
        run: find dist -type h

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: my-artifact
