name: CI

on: [push, pull_request]

permissions:
  pages: write
  contents: write
  id-token: write

jobs:
  build:
    environment:
      name: master
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Packages
        run: npm run build

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d dist -u "mk360 <hamoudi191@hotmail.fr>"
          echo ${{ steps.deployment.outputs.page_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
